name: ${project.name}
main: com.github.siloneco.DisableFriendlyFire
version: ${project.version}
author: siloneco
description: ${project.description}
api-version: 1.13
permissions:
  disablefriendlyfire.apply:
    default: op